application: {{ project_name }}
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

- name: PIL
  version: "latest"
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"

builtins:
- django_wsgi: on

handlers:  
- url: /static
  static_dir: static  

- url: /static/admin/img  
  static_dir: static/admin/img  

- url: /static/admin/css  
  static_dir: static/admin/css  

- url: /static/admin/js  
  static_dir: static/admin/js 

env_variables:
  DJANGO_SETTINGS_MODULE: '{{ project_name }}.settings'